### ISSUE TITLE
Name of the new organization

### ISSUE THREAD

**Issue by blegat** [JuliaStochOpt/StructDualDynProg.jl#15]
As discussed on [Gitter](https://gitter.im/JuliaOpt/StructDualDynProg.jl), we would like to create a new Github organization for Stochastic Optimization in Julia.
Here are the current suggestion of naming:

- JuliaStochSolver :+1: 
- JuliaStochOpt :tada: 
- JuliaOptStoch :heart: 

Use the symbol on the right of name to vote for it !

**Comment by frapac** [comment]
Good initiative!!
Personally I'm in favor of 🎉, or, if you prefer it, I would be ok with ❤️

**Comment by odow** [comment]
JuliaOptStoch might be a little too close to JuliaOpt

**Comment by joaquimg** [comment]
I like this part, since it would be using JuMP...

**Comment by trigaut** [comment]
@frapac +1
